services:

  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # - /srv/baton_media:/backend/media
      # - /srv/baton_static:/srv/baton_static
      - ~/baton_media:/backend/media
      - ~/baton_static:/srv/baton_static
      - ./backend:/backend
    ports:
      - "8000:8000"
    networks:
      frontend_network:
        ipv4_address: 172.19.0.3
      backend_network:
        ipv4_address: 172.20.0.6
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes: # comment for prod
      - ./frontend:/app
      # - /app/node_modules
      - frontend_node_modules:/app/node_modules
    environment:
      - FORCE_COLOR=true
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR=true
      - HOST=0.0.0.0
    networks:
      frontend_network:
        ipv4_address: 172.19.0.4
    depends_on:
      - web

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 443:443
    depends_on:
      - web
      - frontend
    networks:
      frontend_network:
        ipv4_address: 172.19.0.2

networks:
  frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16

  backend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  pgadmin_data:
  baton_db_data: {}
  baton_static:
    external: true
  frontend_node_modules: {} # comment for prod